### ISSUE TITLE
I18n dependency

### ISSUE THREAD

**Issue by cimm** [morellon/rrd-ffi#10]
Hi, when I install the gem and run a simple Ruby script that tries to render a RRD graph it breaks because it needs the `i18n` gem. Installing the gem from RubyGems solves that problem but I was wondering why it isn't specified as a dependency in the gemspec? Seems I don't need the gem if all I want to do is write data to a RRD file.

For future reference:

```
/usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- i18n (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@rrd/gems/activesupport-3.1.3/lib/active_support/i18n.rb:2:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@rrd/gems/activesupport-3.1.3/lib/active_support/inflector/transliterate.rb:3:in `<top (required)>'
```

**Comment by morellon** [comment]
Indeed we don't use i18n in this project.
But it seems to be a activesupport dependency in date calculations somehow.
I will try to find a solution for that.
