### ISSUE TITLE
Undefined constant RRD_FILE in example

### ISSUE THREAD

**Issue by denispeplin** [morellon/rrd-ffi#20]
```
./rrd_graph_sample.rb:5:in `block in <main>': uninitialized constant RRD_FILE (NameError)
        from /var/lib/gems/1.9.1/gems/rrd-ffi-0.2.13/lib/rrd.rb:18:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rrd-ffi-0.2.13/lib/rrd.rb:18:in `graph'
        from ./rrd_graph_sample.rb:4:in `<main>'
```

Will try to guess what it is and where it should be defined...

**Comment by denispeplin** [comment]
Understand, RRD_FILE is just the name of the '*.rrd' the file.
